# Generated by Django 6.1.1 on 2026-09-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_is_paid_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
