# Generated by Django 6.1.1 on 2026-10-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_sizes_product_size_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Select available sizes', max_length=50, null=True),
        ),
    ]
