# Generated by Django 6.1.1 on 2026-09-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
